In [1]:
import pandas as pd

df = pd.read_csv("products_catalog.csv")

print("==== 5 Baris Pertama ====\n", df.head())
print("\n==== Info Dataset ====\n", df.info())
print("\n==== Statistik Deskriptif ====\n", df.describe(include="all"))
print("\n==== Nama Kolom ====\n", df.columns)

==== 5 Baris Pertama ====
    ProductID                                        ProductName ProductBrand  \
0   10017413  DKNY Unisex Black & Grey Printed Medium Trolle...         DKNY
1   10016283  EthnoVogue Women Beige & Grey Made to Measure ...   EthnoVogue
2   10009781  SPYKAR Women Pink Alexa Super Skinny Fit High-...       SPYKAR
3   10015921  Raymond Men Blue Self-Design Single-Breasted B...      Raymond
4   10017833  Parx Men Brown & Off-White Slim Fit Printed Ca...         Parx

   Gender  Price (INR)  NumImages  \
0  Unisex        11745          7
1   Women         5810          7
2   Women          899          7
3     Men         5599          5
4     Men          759          5

                                         Description PrimaryColor
0  Black and grey printed medium trolley bag, sec...        Black
1  Beige & Grey made to measure kurta with churid...        Beige
2  Pink coloured wash 5-pocket high-rise cropped ...         Pink
3  Blue self-design bandhgala suitBlue self-desig...         Blue
4  Brown and off-white printed casual shirt, has ...        White
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12491 entries, 0 to 12490
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ProductID     12491 non-null  int64
 1   ProductName   12491 non-null  object
 2   ProductBrand  12491 non-null  object
 3   Gender        12491 non-null  object
 4   Price (INR)   12491 non-null  int64
 5   NumImages     12491 non-null  int64
 6   Description   12491 non-null  object
 7   PrimaryColor  11597 non-null  object
dtypes: int64(3), object(5)
memory usage: 780.8+ KB

==== Info Dataset ====
 None

==== Statistik Deskriptif ====
            ProductID                                  ProductName  \
count   1.249100e+04                                        12491
unique           NaN                                        10761
top              NaN  Parx Men Blue Slim Fit Checked Casual Shirt
freq             NaN                                           16
mean    9.917160e+06                                          NaN
std     1.438006e+06                                          NaN
min     1.012060e+05                                          NaN
25%     1.006215e+07                                          NaN
50%     1.015463e+07                                          NaN
75%     1.021565e+07                                          NaN
max     1.027514e+07                                          NaN

          ProductBrand Gender   Price (INR)     NumImages  \
count            12491  12491  12491.000000  12491.000000
unique             677      6           NaN           NaN
top     Indian Terrain  Women           NaN           NaN
freq               971   5126           NaN           NaN
mean               NaN    NaN   1452.660956      4.913698
std                NaN    NaN   2118.503976      1.092333
min                NaN    NaN     90.000000      1.000000
25%                NaN    NaN    649.000000      5.000000
50%                NaN    NaN    920.000000      5.000000
75%                NaN    NaN   1499.000000      5.000000
max                NaN    NaN  63090.000000     10.000000

                                              Description PrimaryColor
count                                               12491        11597
unique                                              10435           27
top     Blue medium wash 5-pocket mid-rise jeans, clea...         Blue
freq                                                   54         3443
mean                                                  NaN          NaN
std                                                   NaN          NaN
min                                                   NaN          NaN
25%                                                   NaN          NaN
50%                                                   NaN          NaN
75%                                                   NaN          NaN
max                                                   NaN          NaN

==== Nama Kolom ====
 Index(['ProductID', 'ProductName', 'ProductBrand', 'Gender', 'Price (INR)',
       'NumImages', 'Description', 'PrimaryColor'],
      dtype='object')

In [2]:
#Cek Missing Value
print("==== Missing Values ===\n=", df.isnull().sum())
print("\n")

# Tangani missing values
df['ProductBrand'] = df['ProductBrand'].fillna("Unknown")
df['Gender'] = df['Gender'].fillna("Unisex")
df['PrimaryColor'] = df['PrimaryColor'].fillna("Unknown")
print("Missing Values setelah imputasi:")
print(df.isnull().sum())
print("\n")

# Hapus duplikat berdasarkan ProductID
before = len(df)
df = df.drop_duplicates(subset='ProductID')
after = len(df)
print(f"Duplikat dihapus: {before - after}, Sisa data: {after}")
print("\n")

# Drop baris jika harga kosong
before = len(df)
df = df.dropna(subset=['Price (INR)'])
after = len(df)
print(f"Baris dihapus karena harga kosong: {before - after}, Sisa data: {after}")
print("\n")

# Pastikan tipe data benar
df['Price (INR)'] = pd.to_numeric(df['Price (INR)'], errors='coerce')
df['NumImages'] = pd.to_numeric(df['NumImages'], errors='coerce')
print("Tipe data setelah konversi:")
print(df.dtypes)
print("\n")

# Final check
print("==== Missing Values (final) ====")
print(df.isnull().sum())
print("\n")

print("==== Preview Data ====")
print(df.head())

==== Missing Values ===
= ProductID         0
ProductName       0
ProductBrand      0
Gender            0
Price (INR)       0
NumImages         0
Description       0
PrimaryColor    894
dtype: int64


Missing Values setelah imputasi:
ProductID       0
ProductName     0
ProductBrand    0
Gender          0
Price (INR)     0
NumImages       0
Description     0
PrimaryColor    0
dtype: int64


Duplikat dihapus: 0, Sisa data: 12491


Baris dihapus karena harga kosong: 0, Sisa data: 12491


Tipe data setelah konversi:
ProductID        int64
ProductName     object
ProductBrand    object
Gender          object
Price (INR)      int64
NumImages        int64
Description     object
PrimaryColor    object
dtype: object


==== Missing Values (final) ====
ProductID       0
ProductName     0
ProductBrand    0
Gender          0
Price (INR)     0
NumImages       0
Description     0
PrimaryColor    0
dtype: int64


==== Preview Data ====
   ProductID                                        ProductName ProductBrand  \
0   10017413  DKNY Unisex Black & Grey Printed Medium Trolle...         DKNY
1   10016283  EthnoVogue Women Beige & Grey Made to Measure ...   EthnoVogue
2   10009781  SPYKAR Women Pink Alexa Super Skinny Fit High-...       SPYKAR
3   10015921  Raymond Men Blue Self-Design Single-Breasted B...      Raymond
4   10017833  Parx Men Brown & Off-White Slim Fit Printed Ca...         Parx

   Gender  Price (INR)  NumImages  \
0  Unisex        11745          7
1   Women         5810          7
2   Women          899          7
3     Men         5599          5
4     Men          759          5

                                         Description PrimaryColor
0  Black and grey printed medium trolley bag, sec...        Black
1  Beige & Grey made to measure kurta with churid...        Beige
2  Pink coloured wash 5-pocket high-rise cropped ...         Pink
3  Blue self-design bandhgala suitBlue self-desig...         Blue
4  Brown and off-white printed casual shirt, has ...        White